# FIRECUBE_TEMPLATE_LICENSE_HEADER_BEGIN
# Copyright 2025-2026 EUMETSAT
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# FIRECUBE_TEMPLATE_LICENSE_HEADER_END
<!-- Generated by `firecube plugins create` with firecube {firecube_version}. -->
# {start_case_name} Ingestor Plugin

> **This plugin project is incomplete.** Implement `{hook_summary}` before this plugin can produce output. Until then, ingestion runs raise `NotImplementedError` the first time it is called.{extra_incomplete_note}

## What this plugin does

<!-- TODO: write a one-line summary of what {start_case_name} ingests and emits. -->

## Development

This project has its own Python environment. Run every `firecube` command in
this README from this directory through `uv run`, so the plugin, Firecube, and
the CLI all resolve from the same environment. To install the plugin into an
existing Firecube environment instead, activate that environment and run
`firecube plugins install --editable .` without `uv run`.

```bash
uv sync
```

Implement `{hook_summary}` in the generated ingestor, then add behavior-based
tests for the source data and output contract.

```bash
uv run pytest
uv run ruff check .
uv run pyright
```

## Install into Firecube

```bash
uv run firecube plugins install --editable .
uv run firecube plugins list
uv run firecube plugins describe {plugin_name}
uv run firecube ingest {plugin_name} --show-options
```

`firecube plugins describe` should list `[ENGINE]` options. If you add plugin-specific options via a `PluginConfig` subclass, they will appear under `[PLUGIN]`.

## Run a local ingestion

After the implementation and tests pass, run:

```bash
uv run firecube ingest {plugin_name} \
  --input-data /path/to/your/input \
  --target file:///tmp/{plugin_name}_out{output_suffix} \
  --product-name {plugin_name} \
  --output-format {output_format} \
  --write-mode {write_mode_default}
```

- `--input-data` takes a directory or a single file. Discovery picks up `.zip`,
  `.h5`, `.nc`, `.nc4`, `.hdf`, and `.he5` files, and HDF5 files without those
  extensions. For other formats, add a filter such as
  `--input-filters '["*.csv"]'`.
- `--product-name` labels the product. It defaults to `PRODUCT_NAME` in the
  ingestor.
- `--write-mode direct` writes into the target as the run goes. `staged` builds
  the output in a local workspace and publishes it at the end.

{output_check}

## Run again

{run_again}
{parallel_section}
## Other targets

{storage_note}
